extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:prettier/recommended
  - prettier/react
  - prettier/@typescript-eslint
  - prettier/react
